name: Seed Job
on:
  pull_request_target:
    branches:
      - main
    
permissions: read-all
jobs:
  download-repo:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        ref: ${{ github.event.pull_request.head.sha }}
    - name: Checking downloaded repo
      run: ls -la
      
  call-seed-job:
    needs: download-repo
    #if: github.event.review.state == 'approved' && github.event.review.body == 'Run seed job'
    # Update this path to test your workflow. ie. {owner}/{repo}/.github/workflows/seed-job-new-file.yml
    uses: ./.github/workflows/new-file.yml